{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nlweb.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-webapp
  labels:
    {{- include "nlweb.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.ingress.class "alb" }}
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.front.host | quote }}
      http:
        paths:
        - backend:
            serviceName: {{ include "nlweb.fullname" . }}-webapp-svc
            servicePort: {{ .Values.service.webapp.port }}
{{- end }}
