{{- if .Values.ingress.enabled -}}
{{- $fullName := include "nlweb.fullname" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "nlweb.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    {{- range $label, $annotation := .Values.ingress.annotations }}
    {{- if hasPrefix $.Values.ingress.class $label }}
    {{ $label }}: {{ $annotation }}
    {{- end }}
    {{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - secretName: {{ .secretName }}
      hosts:
      {{- if .hosts -}}
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      {{- else -}}
      {{- range $label, $service := $.Values.services }}
        - {{ $service.host | required (printf "The %s service host is required. (--set services.%s.host=YOUR_HOST)" $label $label) | quote }}
      {{- end }}
      {{- end -}}
  {{- end }}
{{- end }}
  rules:
    {{- range $label, $service := .Values.services }}
    {{- $serviceName := printf "%s-%s-%s" (include "nlweb.fullname" $) "svc" $label }}
    - host: {{ $service.host | quote }}
      http:
        paths:
        {{- if $service.ingress }}
        {{- range $service.ingress.paths }}
        - path: {{ . }}
          backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ $service.port }}
        {{- end }}
        {{- else -}}
        - path: ""
          backend:
            serviceName: {{ $serviceName }}
            servicePort: {{ $service.port }}
        {{- end }}
    {{- end }}
{{- end }}
