apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nlweb.fullname" . }}-key-secret
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "nlweb.labels" . | nindent 4 }}
type: Opaque
data:
  nlwSecretKey: {{ .Values.neoload.configuration.secretKey | required "You need to specify a NLW secret key. (--set neoload.configuration.secretKey=mySecretKey)" | toString | b64enc | quote }}