{{- if .Values.mongodb -}}
{{- if .Values.mongodb.usePassword -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nlweb.fullname" . }}-mongo-secret
  namespace: {{ .Release.Namespace }}  
  labels:
    {{- include "nlweb.labels" . | nindent 4 }}
type: Opaque
data:
  username: {{ .Values.mongodb.mongodbUsername | required "You need to specify a MongoDB username. (--set mongodb.mongodbUsername=user)" | b64enc | quote }}
  password: {{ .Values.mongodb.mongodbPassword | required "You need to specify a MongoDB password. (--set mongodb.mongodbPassword=password)" | b64enc | quote }}
{{- end -}}
{{- end -}}