kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Values.name }}-role
  namespace: {{ .Values.name }}
rules:
- apiGroups: [ "", "apps", "extensions" ]
  resources: ["deployments", "replicasets"]
  verbs: ["*"]
- apiGroups: [ "" ]
  resources: ["replicationcontrollers"]
  verbs: ["*"]
