{{- if .Values.registryKey.enabled -}}
{{- $registryKey := printf "{\"auths\": {\"%s\": {\"auth\": \"%s\"}}}" .Values.registryKey.registry (printf "%s:%s" .Values.registryKey.username .Values.registryKey.password | b64enc) | b64enc -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-rk
  namespace: {{ .Release.Name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf $registryKey }}
{{- end }}