kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ .Release.Name }}-role
  namespace: {{ .Release.Name }}
rules:
- apiGroups: [ "", "apps", "extensions" ]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
- apiGroups: [ "", "apps", "extensions" ]
  resources: ["pods", "events"]
  verbs: ["get", "list"]
- apiGroups: [ "" ]
  resources: ["replicationcontrollers"]
  verbs: ["get", "list", "create", "update", "patch", "delete"]
