apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nlweb-dynamic-infrastructure-user.fullname" . }}-nlweb-secrets
  labels:
    {{- include "nlweb-dynamic-infrastructure-user.labels" . | nindent 4 }}
type: Opaque
data:
  NLW_API_TOKEN: {{ .Values.agent.neoloadWebApiToken | required "You need to specify a NeoLoad Web long-term token. (--set agent.neoloadWebApiToken=password)" | b64enc | quote }}
  {{- with .Values.proxy }}
  {{- if .enabled }}
  {{- with .user }}
  {{- if and .value (not .secretName) }}
  PROXY_USERNAME: {{ .value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- with .password }}
  {{- if and .value (not .secretName) }}
  PROXY_PASSWORD: {{ .value | b64enc | quote }}
  {{- end }}
  {{- end }}
  {{- end }}
  {{- end }}
